#
# This file is part of Kaputt.
# Copyright (C) 2008-2012 Xavier Clerc.
#
# Kaputt is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Kaputt is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

COMPILE_FLAGS=-I ../../_build -I ../../_build/src/extensions unix.$(LIB_EXT) bigarray.$(LIB_EXT) nums.$(LIB_EXT) kaputt.$(LIB_EXT) kaputtBigarray.$(MDL_EXT) kaputtNums.$(MDL_EXT) $(FLAGS)
COMPILED_FILES=*.cm* *.o *.jo $(EXECUTABLE)

default: clean compile run

clean::
	@rm -f $(COMPILED_FILES)

compile::
	@$(PATH_OCAML_BIN)/$(COMPILER) $(COMPILE_FLAGS) -o $(EXECUTABLE) source.ml

run::
	@$(RUN)$(EXECUTABLE)
	@rm -f $(COMPILED_FILES)
